version: '3.9'
services: 
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./data-web-server:/usr/share/nginx/html
      - /sys_infra/certs:/etc/nginx/certs
    environment:
      SFTP_HOST: sftp
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: 193.168.145.12
    networks:
      - infra-network
    depends_on:
      - nginx-proxy
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 81:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: azerty
      WORDPRESS_DB_NAME: mydata_db
    volumes:
      - ./data-wordpress:/var/www/html
    depends_on:
      - mariadb
      - web
    networks:
      - infra-network
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: mydata_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: azerty
    ports:
      - 3306:3306
    networks:
      - infra-network
  sftp:
    image: atmoz/sftp:latest
    volumes:
      - ./data-web-server:/home/admin/upload
    ports:
      - 2222:22
    command: admin:admin:1001
    networks:
      - infra-network
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - /sys_infra/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: 193.168.145.12
      ENABLE_HTTPS: "true"
    networks:
      - infra-network
  duplicati:
    image: duplicati/duplicati
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Bruxelles
    volumes:
      - ./duplicati-data:/root/.config/Duplicati
      - ./backups:/backups
      - /sys_infra:/sys_infra
    ports:
      - 8200:8200
    networks:
      - infra-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: azerty
    depends_on:
      - mariadb
    volumes:
      - /sys_infra/certs:/etc/nginx/certs
    networks:
      - infra-network

volumes:
  data-wordpress:
  data-web-server:
  duplicati-data:

networks:
  infra-network:
    driver: bridge
